#if !canImport(ObjectiveC)
import XCTest

extension ArrayTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArrayTests = [
        ("testStringArray", testStringArray),
    ]
}

extension CompactTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CompactTests = [
        ("testBigUInt", testBigUInt),
        ("testUInt128", testUInt128),
        ("testUInt16", testUInt16),
        ("testUInt32", testUInt32),
        ("testUInt64", testUInt64),
        ("testUInt8", testUInt8),
    ]
}

extension EnumTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EnumTests = [
        ("testAssociatedValues", testAssociatedValues),
        ("testSimpleBadCaseId", testSimpleBadCaseId),
        ("testSimpleCaseEnum", testSimpleCaseEnum),
    ]
}

extension IntegerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IntegerTests = [
        ("testBigIntError", testBigIntError),
        ("testBigUIntError", testBigUIntError),
        ("testBool", testBool),
        ("testInt128", testInt128),
        ("testInt16", testInt16),
        ("testInt32", testInt32),
        ("testInt64", testInt64),
        ("testInt8", testInt8),
        ("testUInt128", testUInt128),
        ("testUInt16", testUInt16),
        ("testUInt32", testUInt32),
        ("testUInt64", testUInt64),
        ("testUInt8", testUInt8),
    ]
}

extension OptionalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OptionalTests = [
        ("testArray", testArray),
        ("testBool", testBool),
        ("testInt", testInt),
        ("testString", testString),
    ]
}

extension ScaleCodecTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ScaleCodecTests = [
        ("testExample", testExample),
    ]
}

extension StringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringTests = [
        ("testDecoding", testDecoding),
        ("testEncoding", testEncoding),
        ("testUTF8", testUTF8),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ArrayTests.__allTests__ArrayTests),
        testCase(CompactTests.__allTests__CompactTests),
        testCase(EnumTests.__allTests__EnumTests),
        testCase(IntegerTests.__allTests__IntegerTests),
        testCase(OptionalTests.__allTests__OptionalTests),
        testCase(ScaleCodecTests.__allTests__ScaleCodecTests),
        testCase(StringTests.__allTests__StringTests),
    ]
}
#endif
