#if !canImport(ObjectiveC)
import XCTest

extension ArrayTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArrayTests = [
        ("testInt16", testInt16),
        ("testOptionalBool", testOptionalBool),
        ("testOptionalInt8", testOptionalInt8),
        ("testString", testString),
        ("testUInt8", testUInt8),
    ]
}

extension CompactTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CompactTests = [
        ("testBigUInt", testBigUInt),
        ("testUInt128", testUInt128),
        ("testUInt16", testUInt16),
        ("testUInt32", testUInt32),
        ("testUInt64", testUInt64),
        ("testUInt8", testUInt8),
    ]
}

extension EnumTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EnumTests = [
        ("testAssociatedValues", testAssociatedValues),
        ("testSimpleBadCaseId", testSimpleBadCaseId),
        ("testSimpleCaseEnum", testSimpleCaseEnum),
    ]
}

extension IntegerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IntegerTests = [
        ("testBigIntError", testBigIntError),
        ("testBigUIntError", testBigUIntError),
        ("testBool", testBool),
        ("testInt128", testInt128),
        ("testInt16", testInt16),
        ("testInt32", testInt32),
        ("testInt64", testInt64),
        ("testInt8", testInt8),
        ("testUInt128", testUInt128),
        ("testUInt16", testUInt16),
        ("testUInt32", testUInt32),
        ("testUInt64", testUInt64),
        ("testUInt8", testUInt8),
    ]
}

extension OptionalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OptionalTests = [
        ("testArray", testArray),
        ("testBool", testBool),
        ("testDataEnum", testDataEnum),
        ("testEnum", testEnum),
        ("testInt", testInt),
        ("testOptionalBool", testOptionalBool),
        ("testOptionalString", testOptionalString),
        ("testString", testString),
    ]
}

extension StringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringTests = [
        ("testBadUTF8", testBadUTF8),
        ("testEncodingDecoding", testEncodingDecoding),
        ("testUTF8", testUTF8),
    ]
}

extension StructTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StructTests = [
        ("testComplexStuct", testComplexStuct),
        ("testSimpleStruct", testSimpleStruct),
        ("testWrappedValue", testWrappedValue),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ArrayTests.__allTests__ArrayTests),
        testCase(CompactTests.__allTests__CompactTests),
        testCase(EnumTests.__allTests__EnumTests),
        testCase(IntegerTests.__allTests__IntegerTests),
        testCase(OptionalTests.__allTests__OptionalTests),
        testCase(StringTests.__allTests__StringTests),
        testCase(StructTests.__allTests__StructTests),
    ]
}
#endif
