#if !canImport(ObjectiveC)
import XCTest

extension ArrayTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArrayTests = [
        ("testFixedArray", testFixedArray),
        ("testInt16", testInt16),
        ("testOptionalBool", testOptionalBool),
        ("testOptionalInt8", testOptionalInt8),
        ("testString", testString),
        ("testUInt8", testUInt8),
    ]
}

extension CompactTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CompactTests = [
        ("testTopLevelAPI", testTopLevelAPI),
        ("testUInt1024", testUInt1024),
        ("testUInt128", testUInt128),
        ("testUInt16", testUInt16),
        ("testUInt32", testUInt32),
        ("testUInt64", testUInt64),
        ("testUInt8", testUInt8),
    ]
}

extension DataTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DataTests = [
        ("testFixedData", testFixedData),
        ("testVariableData", testVariableData),
    ]
}

extension EnumTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EnumTests = [
        ("testAssociatedValues", testAssociatedValues),
        ("testSimpleBadCaseId", testSimpleBadCaseId),
        ("testSimpleCaseEnum", testSimpleCaseEnum),
    ]
}

extension FixedTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FixedTests = [
        ("testArrayStructBadSizeErrors", testArrayStructBadSizeErrors),
        ("testDataStructBadSizeErrors", testDataStructBadSizeErrors),
        ("testFixedDataStruct", testFixedDataStruct),
        ("testFixedStringArrayStruct", testFixedStringArrayStruct),
    ]
}

extension IntegerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IntegerTests = [
        ("testBool", testBool),
        ("testInt128", testInt128),
        ("testInt16", testInt16),
        ("testInt256", testInt256),
        ("testInt32", testInt32),
        ("testInt512", testInt512),
        ("testInt64", testInt64),
        ("testInt8", testInt8),
        ("testUInt128", testUInt128),
        ("testUInt16", testUInt16),
        ("testUInt256", testUInt256),
        ("testUInt32", testUInt32),
        ("testUInt512", testUInt512),
        ("testUInt64", testUInt64),
        ("testUInt8", testUInt8),
    ]
}

extension OptionalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OptionalTests = [
        ("testArray", testArray),
        ("testBool", testBool),
        ("testDataEnum", testDataEnum),
        ("testEnum", testEnum),
        ("testInt", testInt),
        ("testOptionalBool", testOptionalBool),
        ("testOptionalString", testOptionalString),
        ("testString", testString),
    ]
}

extension ResultTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ResultTests = [
        ("testBadData", testBadData),
        ("testNestedOptional", testNestedOptional),
        ("testSimple", testSimple),
    ]
}

extension StringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringTests = [
        ("testBadUTF8", testBadUTF8),
        ("testEncodingDecoding", testEncodingDecoding),
        ("testUTF8", testUTF8),
    ]
}

extension StructTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StructTests = [
        ("testComplexStuct", testComplexStuct),
        ("testSimpleStruct", testSimpleStruct),
        ("testWrappedValue", testWrappedValue),
    ]
}

extension TupleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TupleTests = [
        ("testTuple2", testTuple2),
        ("testTuple3", testTuple3),
        ("testTuple4", testTuple4),
        ("testTuple5", testTuple5),
        ("testTupleNestedContainers", testTupleNestedContainers),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ArrayTests.__allTests__ArrayTests),
        testCase(CompactTests.__allTests__CompactTests),
        testCase(DataTests.__allTests__DataTests),
        testCase(EnumTests.__allTests__EnumTests),
        testCase(FixedTests.__allTests__FixedTests),
        testCase(IntegerTests.__allTests__IntegerTests),
        testCase(OptionalTests.__allTests__OptionalTests),
        testCase(ResultTests.__allTests__ResultTests),
        testCase(StringTests.__allTests__StringTests),
        testCase(StructTests.__allTests__StructTests),
        testCase(TupleTests.__allTests__TupleTests),
    ]
}
#endif
