#if !canImport(ObjectiveC)
import XCTest

extension DoubleWidthTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DoubleWidthTests = [
        ("testArithmetic_signed", testArithmetic_signed),
        ("testArithmetic_unsigned", testArithmetic_unsigned),
        ("testBitshifts", testBitshifts),
        ("testConditional_Conformance", testConditional_Conformance),
        ("testConversions", testConversions),
        ("testConversions_SignedMaxP1", testConversions_SignedMaxP1),
        ("testConversions_SignedMinM1", testConversions_SignedMinM1),
        ("testConversions_String", testConversions_String),
        ("testConversions_UnsignedM1", testConversions_UnsignedM1),
        ("testConversions_UnsignedMaxP1", testConversions_UnsignedMaxP1),
        ("testDivideMinByMinusOne", testDivideMinByMinusOne),
        ("testDivision_By0", testDivision_By0),
        ("testExact_Conversions", testExact_Conversions),
        ("testinits", testinits),
        ("testisMultiple", testisMultiple),
        ("testMagnitude", testMagnitude),
        ("testMultiplyMinByMinusOne", testMultiplyMinByMinusOne),
        ("testNested", testNested),
        ("testRemainder_DividingBy0", testRemainder_DividingBy0),
        ("testRemainderReportingOverflow_DividingByMinusOne", testRemainderReportingOverflow_DividingByMinusOne),
        ("testTwoWords", testTwoWords),
        ("testWords", testWords),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DoubleWidthTests.__allTests__DoubleWidthTests),
    ]
}
#endif
