#if !canImport(ObjectiveC)
import XCTest

extension DoubleWidthTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DoubleWidthTests = [
        ("testArithmetic_signed", testArithmetic_signed),
        ("testArithmetic_unsigned", testArithmetic_unsigned),
        ("testBitshifts", testBitshifts),
        ("testConditional_Conformance", testConditional_Conformance),
        ("testConversions", testConversions),
        ("testConversions_String", testConversions_String),
        ("testExact_Conversions", testExact_Conversions),
        ("testinits", testinits),
        ("testisMultiple", testisMultiple),
        ("testMagnitude", testMagnitude),
        ("testNested", testNested),
        ("testRemainderReportingOverflow_DividingByMinusOne", testRemainderReportingOverflow_DividingByMinusOne),
        ("testTwoWords", testTwoWords),
        ("testWords", testWords),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DoubleWidthTests.__allTests__DoubleWidthTests),
    ]
}
#endif
